# This is a basic workflow to help you get started with Actions

name: Deploy to staging environment
on:
  push:
    branches: [ staging ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: [self-hosted,staging-strapi]
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to staging server
        run: |
          cp ${{secrets.STRAPI_ENV_PATH}} ./.env
          docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null || true
          docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null || true
          docker-compose up -d --build --remove-orphans
