name: Deploy to production environment
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: [self-hosted,production-strapi]
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Copy Env file
        run: cp ${{secrets.STRAPI_ENV_PATH}} ./.env
      - name: Remove old stale images
        timeout-minutes: 15
        run: |
          docker rm -v $(docker ps --filter status=exited -q 2>/dev/null) 2>/dev/null || true
          docker rmi $(docker images --filter dangling=true -q 2>/dev/null) 2>/dev/null || true
      - name: Deploy the latest version
        timeout-minutes: 60
        run: docker-compose up -d --build --remove-orphans
